import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HomeRegistrationForm from '../components/HomeRegistrationForm'
import LanguageSelection from "../components/LanguageSelection";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <LanguageSelection />
        <HomeRegistrationForm />
      </main>

    </div>
  )
}

export default Home
